version: '2'
services:
  blind-robot:
    build: ./flask
    restart: always

  nginx:
    image: nginx
    depends_on:
      - blind-robot
    ports:
      - "127.0.0.1:30007:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
