version: '2'
services:
  red-button:
    build: ./flask
    restart: always

  nginx:
    image: nginx
    depends_on:
      - red-button
    ports:
      - "127.0.0.1:30005:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
