version: '2'
services:
  terminal:
    build: ./service
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./service/logs:/service/logs

  nginx:
    image: nginx
    restart: always
    depends_on:
      - terminal
    ports:
      - "127.0.0.1:30008:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./service/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
